language: python
python: 3.7
dist: xenial
sudo: false
cache: pip
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
before_install:
- pip install tox coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
    python: 3.6
  distributions: sdist bdist_wheel
  user: thomsonreuters-edge
  password:
    secure: SpCg+ldvZYv3nObvKn16A/te0FRyOrPLcS7zpBummJtMNkZlTwvuc5LZW5uzoae4g69JxcfqKmav9A3SxWq77EE0kCvTwIHsLlNifui44RRr48PKDrdsqizY1N2Ltt3gD3jjIpbKa4Uool5Ffwno77H/iNJU27JsQZCuXhkyzK59E/MeUtAo0+rbqiUySADMJFCKGGgDUQdfe4qPOdi8t9wOXwnqnogHDbDXdXUML+eM28DGIqD7SLacoq/HATAc0gGhFdpifP40mYqM936CFXTytvgmY3jVOSjFIpim4AjZyK68pIHEIOWbwXVHn6/PSUheMu1UoS157ywa2qfyDmdr7Nlf+qbuw0CE38AgDys6ButV/rlibVsiVcmdeA0eIkgWEEIQQ2IgsnBuIOv9nD2pukYtxYl+Vwbb8J8DTEBvXbPIQtxFUnHJLPUYd7aQk4z7oiBSl4ORfCXkJ6o1ZOngODkbAx1DRoo+tvqp7ihZXSsBajQUa71v1X0YvBI7a/2UtbqRNzEne/hVg0gTAdoQh4FhOeFQkv5fu8AyMRVDwlx0o3S2K48JeBgx1p/jK1rX64038Q6dCU29+gCgDH3PF/yQ7NX0WuYZdrBQ4JCxU8QcnyZtvBye63piZkREOwVbiM9y1AKelW92k0gVDNMBN4un/+aXF2c0Kqwh94E=
