name: GitHub Python Build
run-name: ${{ github.actor }} build and unittest
on: [push]
jobs:
  build:
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install prereq
        run: pip install tox coveralls
      - name: Run python tests
        run: tox -e ${{ env.python }}
